package com.vcheck.sdk.core.domain

enum class ProviderLogicCase {
    ONE_PROVIDER_NO_COUNTRIES,
    ONE_PROVIDER_ONE_COUNTRY,
    ONE_PROVIDER_MULTIPLE_COUNTRIES,
    MULTIPLE_PROVIDERS_NO_COUNTRIES,
    MULTIPLE_PROVIDERS_PRESENT_COUNTRIES
}